apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: << IAM Role arn that is attached to the EKS nodes >>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: << ROLE ARN for access to the cluster >>
      username: << Username that will be associated with the role >>
      groups:
        - system:masters
  mapUsers: |
    - userarn: << IAM role of a user >>
      username: << User name taht will be associated in EKS logs. >>
      groups:
        - system:masters